stages:
  - test

tests:
  stage: test
  image: 'fedora:latest'
  script:
    - dnf install -y pipenv
    - pipenv install --ignore-pipfile
    - pipenv run flake8 --show-source src/ tests/
    - pipenv run python3 setup.py install # needed to run tests
    - pipenv run pytest tests/
