stages:
  - test

tests:
  stage: test
  image: 'fedora:latest'
  script:
    - dnf install -y pipenv
    - pipenv install --ignore-pipfile
    - pipenv shell
    - flake8 --show-source src/ tests/
    - pytest tests/
