stages:
  - check

flake8:
  stage: check
  image: 'fedora:latest'
  script:
    - dnf install -y python3-pipenv
    - pipenv install --ignore-pipfile
    - flake8 --show-source src/ tests/
    - pytest tests/
