name: "Run Gin"

on:
  push:
    paths:
    - "tests/*.gin.xml"
  pull_request:
    paths:
    - "tests/*.gin.xml"

jobs:
  xmllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --ignore-pipfile --dev
        pipenv run install
    - name: Run Gin
      run: |
        gin manifest tests/com.belmoussaoui.GinTest.gin.xml
        gin manifest tests/org.gnome.design.Palette.gin.xml
